# src/fashion-mnist/params.yaml

download:
  base_url: "http://fashion-mnist.s3-website.eu-central-1.amazonaws.com"
  output_dir: "../../data/fashion-mnist/raw"

process:
  raw_dir: "../../data/fashion-mnist/raw"
  output_dir: "../../data/fashion-mnist/processed"
  sample_fraction: 0.5  # Use 50% of the dataset

analyze:
  data_dir: "../../data/fashion-mnist/processed"
  output_file: "../../data/fashion-mnist/metadata.json"
