download:
  dataset_name: "unsloth/Radiology_mini"
  output_dir: "../../data/roco-radiology/raw"
  num_samples: 500

process:
  raw_dir: "../../data/roco-radiology/raw"
  output_dir: "../../data/roco-radiology/processed"
  stats_file: "../../data/roco-radiology/processed/process_stats.json"
  train_split: 0.8
  prompt_name: "radiology-vlm-prompt"
  prompt_version: 3

analyze:
  data_dir: "../../data/roco-radiology/processed"
  stats_file: "../../data/roco-radiology/processed/process_stats.json"
  output_file: "../../data/roco-radiology/metadata.json"
