download:
  dataset_name: "unsloth/Radiology_mini"
  output_dir: "../../data/radiology-mini/raw"
  num_samples: 500

process:
  raw_dir: "../../data/radiology-mini/raw"
  output_dir: "../../data/radiology-mini/processed"
  stats_file: "../../data/radiology-mini/processed/process_stats.json"
  train_split: 0.8
  prompt_name: "radiology-vlm-prompt"
  prompt_version: 2

analyze:
  data_dir: "../../data/radiology-mini/processed"
  stats_file: "../../data/radiology-mini/processed/process_stats.json"
  output_file: "../../data/radiology-mini/metadata.json"