download:
  dataset_name: "boltuix/emotions-dataset"
  output_dir: "../../data/emotion/raw"

process:
  raw_dir: "../../data/emotion/raw"
  output_dir: "../../data/emotion/processed"
  sample_fraction: 0.5  # Use 50% of dataset
  train_split: 0.8
  random_seed: 42

analyze:
  data_dir: "../../data/emotion/processed"
  output_file: "../../data/emotion/metadata.json"