stages:
  process:
    cmd: python scripts/process.py
    deps:
      - scripts/process.py
    params:
      - params.py:
          - DVC_DATA_VERSION
          - DVC_DATA_PATH
          - EMBEDDING_MODEL_NAME
          - EMBEDDING_CHUNK_SIZE
          - EMBEDDING_CHUNK_OVERLAP
          - EMBEDDING_BATCH_SIZE
  analyze:
    cmd: python scripts/analyze.py
    deps:
      - scripts/analyze.py
    params:
      - params.py:
          - DVC_DATA_VERSION
          - DVC_DATA_PATH
          - EMBEDDING_MODEL_NAME
          - EMBEDDING_CHUNK_SIZE
          - EMBEDDING_CHUNK_OVERLAP
          - ANALYZE_OUTPUT_FILE
    metrics:
      - ../../data/opencloudhub-readmes-embeddings/metadata.json:
          cache: false
