stages:
  process:
    cmd: python scripts/process.py
    deps:
      - scripts/process.py
      # Remove dependency on local data since we fetch via dvc.api
    params:
      - data
      - data
      - embedding
      - pgvector
    # No outs - data goes directly to pgvector
    
  analyze:
    cmd: python scripts/analyze.py
    deps:
      - scripts/analyze.py
    params:
      - data
      - data
      - embedding
    metrics:
      - ../../data/opencloudhub-readmes-embeddings/metadata.json:
          cache: false