# pipelines/wine-quality/params.yaml

download:
  files:
    - name: "winequality-red.csv"
      url: "https://raw.githubusercontent.com/shrikant-temburwar/Wine-Quality-Dataset/master/winequality-red.csv"
    - name: "winequality-white.csv"
      url: "https://raw.githubusercontent.com/shrikant-temburwar/Wine-Quality-Dataset/master/winequality-white.csv"
  output_dir: "../../data/wine-quality/raw"

process:
  raw_dir: "../../data/wine-quality/raw"
  output_dir: "../../data/wine-quality/processed"
  sample_fraction: 1.0  # Use full dataset
  test_size: 0.2  # 80/20 train/val split
  random_state: 42

analyze:
  data_dir: "../../data/wine-quality/processed"
  output_file: "../../data/wine-quality/metadata.json"
